"use strict";
exports.__esModule = true;
var Aluno_1 = require("./Aluno");
var Professor_1 = require("./Professor");
var al;
al = new Aluno_1.Aluno();
al.setNome("Edson");
al.setCurso("Generates");
al.setEmail("Edson@Edson.com.br");
al.setTelefone("+55 97070-7070");
al.setNumRegistro(7070);
al.setAnoMatricula(2019);
console.log(al);
var pr;
pr = new Professor_1.Professor();
pr.setNome("Cleiton");
pr.setAreaFormacao("Enjienieiro da compiuteichion");
pr.setEmail("cleiton@cleiton.com");
pr.setTelefone("+55 91234-5678");
pr.setNumRegistro(816111);
pr.setValorHora(124);
console.log(pr);
